### ISSUE TITLE
[WARN] .File.UniqueID on zero object

### ISSUE THREAD

**Issue by ttnny** [matcornic/hugo-theme-learn#329] opened 2019-09-12 05:30 UTC
Not sure if anyone got this warning?

**`.File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}`**

I have done some quick checks and it seems this doesn't affect page generation.

**Comment by matalo33** [comment] 2020-02-01 23:01
Duplicate of #350

**Closed by matalo33** 2020-02-01 23:01 UTC
Labels: duplicate
