### ISSUE TITLE
Which version of the Theme am I running?

### ISSUE THREAD

**Issue by pgorod** [matcornic/hugo-theme-learn#174] opened 2018-10-09 09:38 UTC
Sorry for the really basic question, but what is the "correct" way to know which version of Theme Learn I have installed on my site, so I can check if it is the latest?

I know I can compare file timestamps or contents, but I was wondering if there is a "proper" way to determine this, or perhaps we could add one? I suggest simply writing it on the README. Thanks.

**Comment by pgorod** [comment] 2018-10-09 17:32
Hmm 🤔 thanks for your answer, but I don't think this approach can work - I have my entire site on my own Git source control, not just the theme. So I get my commit numbers, my commit history, etc. I've made hundreds of commits after bringing in the Theme files.

I've seen some open-source projects simply keeping a version.txt file on the root, and updating that file every time they release.

**Comment by matalo33** [comment] 2018-10-09 18:09
Okay, in that case you would need to clone a fresh version of the theme and compare with the version you have.

You could also delete the theme from _your_ git repository and then either

- Create a symlink from the themes/ folder in your repository to the fresh checkout of the theme (easier)
- Learn how to use git submodules (harder)

**Comment by pgorod** [comment] 2018-10-10 09:00
I can't delete/symlink the files because my site is automatically deployed on Netlify and it needs to be straightforward.

But please take a step back and consider - there are tons of ways to check, laboriously, which files I have. I can `diff` two directories. I can pull the new files and ask `git` to tell me the difference. But notice the level of complexity we're reaching when I ask "so, which version is this?" and I am told to `git rev-parse HEAD`. I love git, but...

Please consider my suggestion of adding this into a file. 

If the Theme opts not to do it, I will just do it for my project, as a comment in my `config.toml`, near the spot where I reference the Theme. I am looking for a simple, direct way to check, nothing more. I believe I am not the only one, this would be a good project policy. But if you don't like my suggestion, that's ok, i won't insist anymore. 

Thanks anyway, great job you're doing here with this excellent Theme!

**Comment by matalo33** [comment] 2018-11-02 00:30
Sure thing, happy to discuss this more.

Currently I have a small amount of spare time to help out the repository owner. I can review PRs, answer some support issues, etc. This doesn't really extend to doing full release planning and management.

Maybe I get to review one or two small PRs per week. This means the version / changelog file will basically be a duplicate of what's in the git history, and if it's just a duplicate it doesn't offer any additional benefit.

You say you are using Netlify builds currently. If you used this theme repository as a git submodule on your repository would your Netlify build be able to pull the git submodule at build time? Because you only take the repository at a specific git commit you are safe from accidental upgrades. When you want to test your site against a new version you `git submodule update --remote` and then test your site against the latest version of the theme before publishing.

I use this workflow on a private site at my employer and it works very well.

* We don't have to maintain a copy of the repo or manually copy files
* We have fixed commit-in-time version of the repo
* Updating to latest is one command

**Comment by pgorod** [comment] 2018-11-02 10:21
I see many advantages in your scheme. I am not familiar with git submodules, but they do seem appropriate for this.

However I still prefer to avoid any additional layer of complexity here. I have to worry about Netlify deploys, but also about letting my users edit the site with as little knowledge of git, or of my Docs project, as possible. Many of my users are touching git for the first time just for the purposes of contributing Docs to our site.

In our main project (the one for which we build Docs with Learn theme), SuiteCRM, this is what we do for releases:

https://github.com/salesagility/SuiteCRM/commit/611f7ac9c599768c57fc4cea2240ef27eec55078

This is always the last commit to go into a release, and the one that gets the GitHub tag for the release number. It's simple, and dependable.

But really, I don't mind if you close this Issue and choose what you think is better for this project here, not for mine. Git submodules might be the way to go, and they are probably not as complicated as they seem to me :-)

Thanks for having this discussion with me, and for the time you're devoting to the Theme.

**Comment by matalo33** [comment] 2018-11-02 15:41
I also noticed last night that @matcornic occasionally published a 'version' of the theme using the [releases page in the project](https://github.com/matcornic/hugo-theme-learn/releases). Would that be of any assistance?

I'm not necessarily saying that submodules are best for the project, but they might be worth considering. This was also my first use of submodules and they are working well in my situation.

If others really want a versioned release model we can focus more on that.

**Comment by matalo33** [comment] 2019-04-01 21:37
Reviving this thread slightly, there's now something resembling a "release" process where I'm bunching what I feel is a sensible amount of change into a github release.

If git submodule or commit-hash-pin methods are not working for you then you could now download the packaged versions from github.

**Closed** 2020-09-10 17:03 UTC
Labels: support
