### ISSUE TITLE
Ordering menu

### ISSUE THREAD

**Issue by xafardero** [matcornic/hugo-theme-learn#2] opened 2016-05-03 08:31 UTC
Hi, I'm using the template and in a new site when I run this commands:

```
hugo new --kind chapter codestyles/index.md
hugo new --kind chapter git/index.md
hugo new --kind chapter features/index.md
```

And if I try to order assigning a different weigth nothing changes, looks like the other is always the alphabetical  A to Z.

I'm new at Go and Hugo maybe im doing something wrong, but seems like not!

**Comment by matcornic** [comment] 2016-05-03 11:53
Hello Xaf,

I'll look into that. Since you used weigth and it does not work, it may be a bug.
Meanwhile, one simple solution is prefixing your folders with a number. Then, if you don't want the numbers to be in the path, create [aliases](https://gohugo.io/extras/aliases/).

**Comment by TimNN** [comment] 2016-05-18 06:55
I'm also encountering this issue (weight does not work with chapters).

**Comment by TimNN** [comment] 2016-05-18 07:16
It looks like the problem is that `.Site.Sections` is an map of `pageName` to `WeightedPages` objects and not a `WeightedPages` object.

**Comment by TimNN** [comment] 2016-05-18 09:53
I tried to use `{{ range $key , $value := sort .Site.Sections "First.Weight" }}` in `menu.html` which I believe *should* work, but fails because "error calling sort: First is neither a struct field, a method nor a map element of type hugolib.WeightedPages".

**Comment by eddie** [comment] 2016-05-23 18:24
@TimNN The sections are just directories right? So they won't have the weight attribute.

**Comment by TimNN** [comment] 2016-05-23 19:08
Yeah, that was why I was trying something like **`First`**`.Weight` (so order the sections by the weight of the first page in the section).

I don't know where I got the `First` from - I believe I found it in some go documentation but I can't seem to find it again.

**Comment by eddie** [comment] 2016-05-23 19:55
@TimNN Printing out the sections map gives me this

```map[faq:[{0 }] changelog:[{0 }] intro:[{5 }]]```

Not sure how to apply sort with this however :)

**Comment by matcornic** [comment] 2016-05-23 23:10
@TimNN @eddie Yes, it's a map of list of pages, you can't sort it like a list (https://gohugo.io/templates/list/). The `key` is the folder name, the `value` is the list of the pages inside the folder.

My thought was to create a menu automatically from the folder structure of the content, instead of using the Hugo menu functionality (in order to avoid boilerplate in config.toml). As Hugo does not provide (yet) a functionality like this, I based everything on the `.Site.Sections`.

Based on that principle, and my little knowledge about Go Templates, I can't define *right know* a nice and clean solution (but I'm sure there is one 😄 ).

**Comment by Xipas** [comment] 2016-05-24 14:29
Hi, i had the same problem, and ended up changing the menu creation to ` .Site.Menus` 
[Hugo Docs](https://gohugo.io/extras/menus/)

it changes a bit on the page, but i like it better this way.

Menu changed to this (line 16)

```html
  <ul class="topics">
          {{ $page := . }}  
      {{ range .Site.Menus.main }}
      <li class="dd-item  {{ if eq $page.RelPermalink .URL }}active{{ end }} {{if in $page.RelPermalink .URL }}parent{{ end }}"    
      data-nav-id="{{.URL}}">
        <a href="{{.URL}}">
          <span>
             {{ .Pre  }}
            {{ .Name }} 
              {{ if .Site.Params.showVisitedLinks}}  <i class="fa fa-check read-icon"> {{ end }} </i>
           </span>
        </a>
        {{ if .HasChildren }} 
        <ul>
          {{ range .Children}}
          <li class="dd-item {{ if eq $page.RelPermalink .URL }}active{{ end }}"  data-nav-id="{{.URL}}">
            <a href="{{.URL}}">
              <span>{{ .Name  }}    {{ if .Site.Params.showVisitedLinks}} <i class="fa fa-check read-icon"></i> {{ end }} </span>
            </a>
          </li>
          {{ end }}
        </ul> 
        {{ end }} 
      </li> 
      {{ end }}
    </ul>
```
since i do not like having the menu defined on `config.toml`
my content page header changed to this

```yaml
--- 
title : "Title to show"
next: /sobre/intro
chapter: true 
menu:
  main:
    identifier : "Unique_ID_OF_PAGE"
    weight: 5
    name : "Title to show"
    pre : '<b>1.</b>'
---
```

and the child's (we can have unlimited levels, using the `identifier` and the `parent`, however the menu design only show 2 levels for now)

```yaml
--- 
title: What is this Hugo theme ?
prev: /sobre
next: /sobre/requesitos 
menu:
  main:
    identifier : "Unique_ID_OF_PAGE"
    parent: 'Unique_ID_OF_PARENT'
    weight: 5
    name : "What is this Hugo theme"
---
```


and a bug fix on header.html (on the breadcrumb creator) line 51
```html
    {{ $type := .Params.menu.main.parent }}
                {{ $relLink := .RelPermalink }}
                {{ range $name , $value := .Site.Menus.main }}
               
                 {{ if eq $value.Identifier $type }} 
                    {{ if ne $relLink $value.URL }}
                <a href="{{  $value.URL }}" itemprop="url"><span itemprop="title"> <b>{{  $value.Name }}</b></span></a> <i class="fa fa-angle-right"></i>
                    {{ end }}
                  {{ end }}
                {{ end }}
```


and now i have the same menu, and the weight working.

I still working to reduce the duplication on top of content pages, since we have `Title`and menu `name` with the same values.

i think i just need replace all uses of `.Title` with the menu value `.Params.menu.main.name`, however havent done that yet, so now sure about that.

**Comment by Xipas** [comment] 2016-05-25 23:30
I created a pr #5 with this changes and keep compatibility to folder way, and with 3rd level menu, however, still have a decision to make if we wanna use go this way.

**Comment by tandibar** [comment] 2016-08-26 13:58
I think it would be much nicer to go with the default hugo way. Would love to see this PR merged.

**Comment by kamilchm** [comment] 2016-08-31 14:00
I posted an alternative solution in https://github.com/matcornic/hugo-theme-learn/pull/8

**Closed** 2016-10-02 16:12 UTC
