### ISSUE TITLE
NPE error when image refs don't have any query parameters

### ISSUE THREAD

**Issue by jaredstehler** [matcornic/hugo-theme-learn#382] opened 2020-03-12 17:19 UTC
I am encountering a javascript error whenever I have a page with an image reference which doesn't contain any query parameters:
```
hugo-learn.js?1584033441:25 Uncaught TypeError: Cannot read property 'featherlight' of undefined
    at HTMLImageElement.<anonymous> (hugo-learn.js?1584033441:25)
    at HTMLImageElement.<anonymous> (jquery-3.3.1.min.js?1584033441:2)
    at Function.each (jquery-3.3.1.min.js?1584033441:2)
    at w.fn.init.each (jquery-3.3.1.min.js?1584033441:2)
    at w.fn.init.wrap (jquery-3.3.1.min.js?1584033441:2)
    at hugo-learn.js?1584033441:22
```

This is caused by the function which extracts parameters returning undefined.

**Comment by fritzmg** [comment] 2020-03-12 20:46
Duplicate of #379

**Closed** 2020-06-01 12:00 UTC
